on:
  push:
  pull_request:

name: Run Tests

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: install idris2-pack
        run: |
          set -o pipefail
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/stefan-hoeck/idris2-pack/main/install.bash)"
          echo "$HOME/.pack/bin" >> $GITHUB_PATH
          echo | source $HOME/.profile && $HOME/.pack/bin/idris2 --version
      - uses: actions/checkout@v3
      - name: Test
        run: pack test control-spec
