on:
  push:
    paths:
      - "**.idr"
      - "**.yaml"
  pull_request:
    branches: [main]

name: Run Tests

jobs:
  test:
    env:
      DETECTED_SCHEME: racket
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: Bogdanp/setup-racket@v1.10
        with:
          architecture: "x64"
          distribution: "full"
          variant: "CS"
          version: "stable"
      - name: install idris2-pack
        run: |
          set -o pipefail
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/dannypsnl/idris2-pack/main/install.bash)"
          echo "$HOME/.pack/bin" >> $GITHUB_PATH
          echo | source $HOME/.profile && $HOME/.pack/bin/idris2 --version
      - uses: actions/checkout@v3
      - name: Test
        run: pack test control-spec
